[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 302
  force = true

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 302
  force = true
